version: 1.0.{build}
image: Visual Studio 2017
configuration:
    - Debug
    - Release
platform:
    - x86
    - x64
environment:
    matrix:
    #    - Toolset: v140
        - Toolset: v150
install:
- ps: |
    git submodule init
    git submodule update
    ############################################################################
    # All external dependencies are installed in C:\projects\deps
    ############################################################################
    mkdir C:\projects\deps
    cd C:\projects\deps
    $triplet = "$env:PLATFORM"+"-windows"
    # Kinect Headers
    mkdir Headers
    appveyor DownloadFile 'https://gist.github.com/TinyTinni/2209b0baaec9ef1d61e729b757f9210f/archive/bee0361721a66856542274f59ad3ed733b8a9c43.zip' -FileName Headers.zip
    7z.exe e Headers.zip -o*
    # Protobuf
    vcpkg install --triplet "$triplet" protobuf
    # ffmpeg
    if ($env:PLATFORM -eq "x64")
    {
        appveyor DownloadFile 'https://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-3.3.3-win64-dev.zip' -Filename ffmpeg.zip
        appveyor DownloadFile 'https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-3.3.3-win64-shared.zip' -Filename ffmpeg-binary.zip
        $ffmpeg_dir = "ffmpeg-3.3.3-win64-dev"
        $ffmpeg_binary_dir = "ffmpeg-3.3.3-win64-shared"
    }
    else
    {
        appveyor DownloadFile 'https://ffmpeg.zeranoe.com/builds/win32/dev/ffmpeg-3.3.3-win32-dev.zip' -Filename ffmpeg.zip
        appveyor DownloadFile 'https://ffmpeg.zeranoe.com/builds/win32/shared/ffmpeg-3.3.3-win32-shared.zip' -Filename ffmpeg-binary.zip
        $ffmpeg_dir = "ffmpeg-3.3.3-win32-dev"
        $ffmpeg_binary_dir = "ffmpeg-3.3.3-win32-shared"
    }
    7z.exe x ffmpeg.zip -o*
    7z.exe x ffmpeg-binary.zip -o*
    cd ffmpeg
    ren $ffmpeg_dir ffmpeg
    cd ..\
    # in C:\project\deps
    mkdir runtime
    mv ("C:\projects\deps\ffmpeg-binary\"+$ffmpeg_binary_dir+"\bin\*.dll") ".\runtime"
    cd .\runtime
    dir
before_build:
- ps: |
    ########################    
    $generator = switch ($env:TOOLSET)
    {
        "v150" {"Visual Studio 15 2017"}
        "v140" {"Visual Studio 14 2015"}
        "v120" {"Visual Studio 12 2013"}
        "v110" {"Visual Studio 11 2012"}
        "v100" {"Visual Studio 10 2010"}
    }
    if ($env:PLATFORM -eq "x64")
    {
        $generator = "$generator Win64"
    }
    cd $env:APPVEYOR_BUILD_FOLDER
    cmake --version
    md build -Force | Out-Null
    cd build 
    cmake -G "$generator"  -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_CONFIGURATION_TYPES="Debug;Release" -DKinectSDK_INCLUDE_DIRS="C:\projects\deps\Headers" -DBUILD_GUI=OFF -DBUILD_TESTS=ON -DFFMPEG_DIR="C:\projects\deps\ffmpeg\ffmpeg" -DCMAKE_EXE_LINKER_FLAGS="/SAFESEH:NO" -DCMAKE_MODULE_LINKER_FLAGS="/SAFESEH:NO" -DCMAKE_STATIC_LINKER_FLAGS="/SAFESEH:NO" -DCMAKE_SHARED_LINKER_FLAGS="/SAFESEH:NO" ..
build_script:
    - ps: cmake --build . --config $env:CONFIGURATION
    
test_script:
- ps: |
    $env:path += ";C:\projects\deps\runtime"
    ctest -C $env:CONFIGURATION --output-on-failure
    